# Generated by Django 3.2.3 on 2021-06-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('idEmpleo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de empleado')),
                ('nombreEmpleo', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='apellido')),
                ('correo', models.CharField(max_length=60, verbose_name='correo')),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleo')),
            ],
        ),
    ]
