# Generated by Django 3.2.3 on 2021-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='idEmpleo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de emplea'),
        ),
        migrations.AlterField(
            model_name='empleo',
            name='nombreEmpleo',
            field=models.CharField(max_length=50, verbose_name='Nombre Cate'),
        ),
    ]
